alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: www.wellbee.live
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: frontend
    match:
      path:
        prefix: /
  - component:
      name: frontend
      rewrite: /public/index.html
    match:
      path:
        prefix: /*
name: open-soft-front
region: blr
static_sites:
- build_command: |
    npm install && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: MT-GC-Open-Soft-2025/frontend
  name: frontend
  output_dir: build
  source_dir: /
